AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3

Style/BlockDelimiters:
  EnforcedStyle: semantic
  FunctionalMethods:
    - before
    - let
    - let!
    - subject
    - watch
    - expect

Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 20
