sudo: required
dist: trusty
language: ruby
cache:
  bundler: true
  directories:
    - node_modules
    - tmp/cache/assets/test/sprockets
rvm:
  - 2.3.1
before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb
  - nvm install 6.9.1
  - npm install npm -g
  - npm install
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
addons:
  postgresql: "9.3"
services:
  - postgresql
script:
  - bundle exec rake db:test:prepare
  - bundle exec rake
  - npm test
