version: '2'
services:
  app:
    build: .
    depends_on:
      - postgres
    command:
      ["./run.sh", "postgres"]
    volumes:
      - .:/usr/src/app
    volumes_from:
      - box
    ports:
      - "3000:3000"

  box:
    image: busybox
    volumes:
      - /box

  postgres:
    image: 'postgres:9.5'
