SF_CLIENT_ID: 'SCICASPER45'
SF_CLIENT_KEY: '031H717'
SF_SITE: 'https://api.cas.org'
SF_TOKEN_PATH: '/scifinder/auth/oauth/token'
SF_PING_PATH: 'scifinder/workflow/services/1.0/maint/ping'
SF_PAT_INF_PATH: 'scifinder/workflow/services/1.0/content/document/patent/'
SF_DOI_INF_PATH: 'scifinder/workflow/services/1.0/content/document/doi/'
SF_CAS_RN_PATH: 'scifinder/workflow/services/1.0/content/substance/rn/'
SF_LK_PAT_PATH: 'scifinder/workflow/services/1.0/linkDetail/document/patent/'
SF_LK_DOI_PATH: 'scifinder/workflow/services/1.0/linkDetail/document/doi/'
SF_LK_CAS_PATH: 'scifinder/workflow/services/1.0/linkDetail/substance/rn/'
SF_ANS_SUB_PATH: 'scifinder/workflow/services/1.0/linkAnswer/substance/'
SF_ANS_REA_PATH: 'scifinder/workflow/services/1.0/linkAnswer/reaction/'
SF_PASS_PHRASE: "\x80l\x03\xCE\x8A\x03\xBD\x19\x14C\xC3\xECAI\xCB\xB3\x8B\xCF\x04\x11\x8C\xFCe\x8F\x0F\x86 s\xD6%#\xBC"
OAUTH_DEBUG: 'false'
